### ISSUE TITLE
DevDB Distribution Scripts Refactor

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#881] opened 2023-03-31 15:45 UTC
Collaborate with DE to streamline DevDB distribution scripts

**Comment by caseysmithpgh** [comment] 2023-04-24 14:47
#792 See 22v2 Issue

**Comment by croswell81** [comment] 2023-05-18 18:27
@caseysmithpgh should this be closed because duplicate of #905?

**Closed** 2023-05-18 19:31 UTC
Labels: GIS
